/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:f278e8e7-fa77-41e6-840a-a2ee7aed7124",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_pPI2qeChI",
    "aws_user_pools_web_client_id": "782r0togvmj2hhkncmefni14q",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vq4qw4vrgba6pmz56ibfcxeyvu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
